melita-rbev/environment-jx-production

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.62
=> melita-it-eshop-frontend to 0.0.62

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.63
=> melita-it-eshop-frontend to 0.0.63

env/requirements.yaml
Promote personal-details-validator-api to version 1.0.40
=> personal-details-validator-api to 1.0.40

env/requirements.yaml
Promote appointment-scheduling-api to version 1.0.29
=> appointment-scheduling-api to 1.0.29

env/requirements.yaml
Promote kyc-service-api to version 1.0.25
=> kyc-service-api to 1.0.25

env/requirements.yaml
Promote eshop-product-api to version 1.0.49
=> eshop-product-api to 1.0.49

env/requirements.yaml
Promote amdocs-ws-api to version 0.3.34
=> amdocs-ws-api to 0.3.34

env/requirements.yaml
Promote ott-service-api to version 1.0.39
=> ott-service-api to 1.0.39

env/requirements.yaml
Promote sandbox to version 0.0.47
=> sandbox to 0.0.47

env/requirements.yaml
Promote kyc-service-api to version 1.0.26
=> kyc-service-api to 1.0.26

env/requirements.yaml
Promote melita-it-eshop-api to version 1.0.85
=> melita-it-eshop-api to 1.0.85

env/requirements.yaml
Promote personal-details-validator-api to version 1.0.41
=> personal-details-validator-api to 1.0.41

env/requirements.yaml
Promote kyc-service-api to version 1.0.27
=> kyc-service-api to 1.0.27

env/requirements.yaml
Promote personal-details-validator-api to version 1.0.42
=> personal-details-validator-api to 1.0.42

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.92
=> melita-it-eshop-frontend to 0.0.92

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.93
=> melita-it-eshop-frontend to 0.0.93

env/requirements.yaml
Promote eshop-product-api to version 1.0.51
=> eshop-product-api to 1.0.51

env/requirements.yaml
Promote appointment-scheduling-api to version 1.0.33
=> appointment-scheduling-api to 1.0.33

env/requirements.yaml
Promote amdocs-ws-api to version 0.3.49
=> amdocs-ws-api to 0.3.49

env/requirements.yaml
Promote melita-it-eshop-api to version 1.0.89
=> melita-it-eshop-api to 1.0.89

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.99
=> melita-it-eshop-frontend to 0.0.99

env/requirements.yaml
Promote melita-it-eshop-api to version 1.0.92
=> melita-it-eshop-api to 1.0.92

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.103
=> melita-it-eshop-frontend to 0.0.103

env/requirements.yaml
Promote eshop-product-api to version 1.0.56
=> eshop-product-api to 1.0.56

env/requirements.yaml
Promote melita-it-eshop-api to version 1.0.95
=> melita-it-eshop-api to 1.0.95

env/requirements.yaml
Promote melita-it-eshop-frontend to version 0.0.107
=> melita-it-eshop-frontend to 0.0.107

env/requirements.yaml
Promote melita-it-eshop-api to version 1.0.97
=> melita-it-eshop-api to 1.0.97

env/requirements.yaml
Promote payment-service-api to version 1.3.0
=> payment-service-api to 1.3.0

env/requirements.yaml
appointment-scheduling-api version: 1.0.49 to 1.0.50
customer-events-ws version: 1.0.9 to 1.0.10
mymelita-frontend version: 0.0.41 to 0.0.46
=> Update requirements.yaml prod
